/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as WithdrawRouteImport } from './routes/withdraw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)

const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)

const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/tasks': typeof TasksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/achievements': typeof AchievementsRoute
  '/referral': typeof ReferralRoute
  '/withdraw': typeof WithdrawRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/tasks': typeof TasksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/achievements': typeof AchievementsRoute
  '/referral': typeof ReferralRoute
  '/withdraw': typeof WithdrawRoute
}

export interface FileRoutesById {
  '__root__': typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/tasks': typeof TasksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/achievements': typeof AchievementsRoute
  '/referral': typeof ReferralRoute
  '/withdraw': typeof WithdrawRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daily' | '/tasks' | '/leaderboard' | '/achievements' | '/referral' | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daily' | '/tasks' | '/leaderboard' | '/achievements' | '/referral' | '/withdraw'
  id: '__root__' | '/' | '/daily' | '/tasks' | '/leaderboard' | '/achievements' | '/referral' | '/withdraw'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  TasksRoute: typeof TasksRoute
  LeaderboardRoute: typeof LeaderboardRoute
  AchievementsRoute: typeof AchievementsRoute
  ReferralRoute: typeof ReferralRoute
  WithdrawRoute: typeof WithdrawRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  TasksRoute: TasksRoute,
  LeaderboardRoute: LeaderboardRoute,
  AchievementsRoute: AchievementsRoute,
  ReferralRoute: ReferralRoute,
  WithdrawRoute: WithdrawRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": ["/", "/daily", "/tasks", "/leaderboard", "/achievements", "/referral", "/withdraw"]
    },
    "/": { "filePath": "index.tsx" },
    "/daily": { "filePath": "daily.tsx" },
    "/tasks": { "filePath": "tasks.tsx" },
    "/leaderboard": { "filePath": "leaderboard.tsx" },
    "/achievements": { "filePath": "achievements.tsx" },
    "/referral": { "filePath": "referral.tsx" },
    "/withdraw": { "filePath": "withdraw.tsx" }
  }
}
ROUTE_MANIFEST_END */
